-- AlterTable
ALTER TABLE `adminuser` ADD COLUMN `active` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `nomeCompleto` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `role` ENUM('MASTER', 'ADMIN', 'EDITOR') NOT NULL DEFAULT 'EDITOR';
