-- CreateTable
CREATE TABLE `Lead` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `companyName` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `city` VARCHAR(191) NULL,
    `state` VARCHAR(191) NULL,
    `segment` VARCHAR(191) NULL,
    `operationSize` VARCHAR(191) NULL,
    `marketTime` VARCHAR(191) NULL,
    `mainChallenge` VARCHAR(191) NULL,
    `growthChallenge` TEXT NULL,
    `diagnosis` JSON NOT NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'new',
    `source` VARCHAR(191) NOT NULL DEFAULT 'site',
    `score` INTEGER NOT NULL DEFAULT 0,
    `leadTemperature` VARCHAR(191) NULL,
    `notes` TEXT NULL,
    `assignedTo` VARCHAR(191) NULL,
    `lastContactAt` DATETIME(3) NULL,
    `nextContactAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `Lead_status_idx`(`status`),
    INDEX `Lead_leadTemperature_idx`(`leadTemperature`),
    INDEX `Lead_segment_idx`(`segment`),
    INDEX `Lead_state_idx`(`state`),
    INDEX `Lead_city_idx`(`city`),
    INDEX `Lead_score_idx`(`score`),
    INDEX `Lead_createdAt_idx`(`createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
